package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/google/go-github/v69/github"
)

func main() {
	const repo string = "hwakabh/repooster"

	fmt.Println("Hello go-github !")

	fmt.Println(">>> Fetching GitHub Personal Access Token ...")
	token, ret := os.LookupEnv("GH_TOKEN")
	if ret != true {
		fmt.Println("Failed to fetch GitHub token, please set GH_TOKEN first.")
		// Note that os.Exit() will not call the logics of `defer`
		os.Exit(1)
	}

	fmt.Println(">>> Initializing go-github Client instances")
	client := github.NewClient(nil).WithAuthToken(token)

	fmt.Printf(">>> Getting commit history of %s ...\n", repo)

	// https://pkg.go.dev/github.com/google/go-github/github#RepositoriesService.ListCommits
	opt := &github.CommitsListOptions{Path: "./README.md"}
	commits, _, err := client.Repositories.ListCommits(context.Background(), strings.Split(repo, "/")[0], strings.Split(repo, "/")[1], opt)
	if err != nil {
		fmt.Println("Failed to fetch list of commits")
		fmt.Println(err)
		os.Exit(1)
	}

	// ListCommits() result has pagenations by default with 30 from latest
	fmt.Printf("Found %v commits in repo with file %s\n", len(commits), opt.Path)
	if len(commits) != 1 {
		fmt.Println("There are several commits in the repo as below, seems not new repository and need not to initialize.")
		for _, commit := range commits {
			// https://pkg.go.dev/github.com/google/go-github/github#RepositoryCommit
			// https://pkg.go.dev/github.com/google/go-github/github#Commit
			fmt.Printf("commit: [ %s ]\n", commit.Commit.GetMessage())
		}
		os.Exit(1)
	}

	fmt.Println(">>> Checking the latest commit message of README")
	latest := commits[len(commits)-1]
	if latest.Commit.GetMessage() != "Initial commit" {
		fmt.Println("Seems that this repository was not generated by `hwakabh/.github` template, skipped the process")
		fmt.Printf("%s | %s\n", latest.GetSHA(), latest.Commit.GetMessage())
		os.Exit(1)
	}

	fmt.Println("Now we can start initialize the repository!")
}
