package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/google/go-github/v69/github"
)

func main() {
	// Fetch CLI args and validations
	args := os.Args
	if len(args) != 2 {
		fmt.Println("Too many arguments, please run `repooster owner/repo`.")
		os.Exit(1)
	}

	if args[1] == "help" {
		fmt.Println("Help menu here")
		os.Exit(1)
	}

	repo := os.Args[1]
	if len(strings.Split(repo, "/")) != 2 {
		fmt.Println("Invalid arguments, argument should be `owner/repo` format.")
		os.Exit(1)
	}

	repoowner := strings.Split(repo, "/")[0]
	reponame := strings.Split(repo, "/")[1]

	fmt.Println("Hello go-github !")

	fmt.Println(">>> Fetching GitHub Personal Access Token ...")
	token, ret := os.LookupEnv("TOKEN")
	if ret != true {
		fmt.Println("Failed to fetch GitHub token, please set GH_TOKEN first.")
		// Note that os.Exit() will not call the logics of `defer`
		os.Exit(1)
	}

	fmt.Println(">>> Initializing go-github Client instances")
	client := github.NewClient(nil).WithAuthToken(token)

	fmt.Printf(">>> Getting commit history of %s ...\n", repo)

	// https://pkg.go.dev/github.com/google/go-github/github#RepositoriesService.ListCommits
	opt := &github.CommitsListOptions{Path: "./README.md"}
	commits, _, listerr := client.Repositories.ListCommits(context.Background(), repoowner, reponame, opt)
	if listerr != nil {
		fmt.Println("Failed to fetch list of commits")
		fmt.Println(listerr)
		os.Exit(1)
	}

	// ListCommits() result has pagenations by default with 30 from latest
	fmt.Printf("Found %v commits in repo with file %s\n", len(commits), opt.Path)
	if len(commits) != 1 {
		fmt.Println("There are several commits in the repo as below, seems not new repository and need not to initialize.")
		for _, commit := range commits {
			// https://pkg.go.dev/github.com/google/go-github/github#RepositoryCommit
			// https://pkg.go.dev/github.com/google/go-github/github#Commit
			fmt.Printf("commit: [ %s ]\n", commit.Commit.GetMessage())
		}
		os.Exit(1)
	}

	fmt.Println(">>> Checking the latest commit message of README")
	latest := commits[len(commits)-1]
	if latest.Commit.GetMessage() != "Initial commit" {
		fmt.Println("Seems that this repository was not generated by `hwakabh/.github` template, skipped the process")
		fmt.Printf("%s | %s\n", latest.GetSHA(), latest.Commit.GetMessage())
		os.Exit(1)
	}

	fmt.Println("Now we can start initialize the repository!")

	fmt.Println(">>> Updating workflow permission for GitHub actions")
	default_workflow_permission := "write"
	can_approve_pull_request_reviews := true
	permissions := &github.DefaultWorkflowPermissionRepository{
		DefaultWorkflowPermissions:   &default_workflow_permission,
		CanApprovePullRequestReviews: &can_approve_pull_request_reviews,
	}
	_, _, editerr := client.Repositories.EditDefaultWorkflowPermissions(context.Background(), repoowner, reponame, *permissions)
	if editerr != nil {
		fmt.Printf("Failed to update default workflow permissions in %s\n", repo)
		fmt.Println(editerr)
		os.Exit(1)
	}
	fmt.Println("OK")

	fmt.Println(">>> Adding branch protection rule to main branch")
	rules := &github.ProtectionRequest{
		RequiredStatusChecks: &github.RequiredStatusChecks{
			Strict: true,
			// https://github.com/google/go-github/issues/2467#issuecomment-1250072559
			Checks: &([]*github.RequiredStatusCheck{}),
		},
		RequiredPullRequestReviews: &github.PullRequestReviewsEnforcementRequest{
			DismissStaleReviews:          false,
			DismissalRestrictionsRequest: nil,
			RequireCodeOwnerReviews:      false,
			RequiredApprovingReviewCount: 0,
		},
		EnforceAdmins: false,
		Restrictions:  nil,
	}
	_, _, updateerr := client.Repositories.UpdateBranchProtection(context.Background(), repoowner, reponame, "main", rules)
	if updateerr != nil {
		fmt.Printf("Failed to update branch protection rule in %s\n", repo)
		fmt.Println(updateerr)
		os.Exit(1)
	}
	fmt.Println("OK")

	fmt.Println(">>> Disabling Wiki/Discussions/Projects tabs from repository")
	// Fetch repository instance
	// https://github.com/google/go-github/blob/master/github/repos.go#L630
	r, _, fetcherr := client.Repositories.Get(context.Background(), repoowner, reponame)
	if fetcherr != nil {
		fmt.Printf("Failed to get information of repository: [ %s ]\n", repo)
		fmt.Println(r)
		os.Exit(1)
	}
	// fmt.Println(r)
	rbody := struct {
		has_discussions bool
		has_projects    bool
		has_wiki        bool
	}{
		false,
		false,
		false,
	}
	_, _, err := client.Repositories.Edit(context.Background(), repoowner, reponame, &github.Repository{
		HasDiscussions: &rbody.has_discussions,
		HasProjects:    &rbody.has_projects,
		HasWiki:        &rbody.has_wiki,
	})
	if err != nil {
		fmt.Printf("Failed to update project tabs in %s\n", repo)
		os.Exit(1)
	}
	fmt.Println("OK")
}
